namespace StompClient
{
    /// <summary>
    ///     Unsubscribe frame for unsubscribing from a given feed on the server
    /// </summary>
    [StompFrameType("UNSUBSCRIBE", StompFrameDirection.ClientToServer)]
    class StompUnsubscribeFrame : StompFrame
    {
        [StompHeaderIdentifier("id")]
        internal string _id;

        /// <summary>
        ///     The Id string generated by the client when originally subscribing to this feed
        /// </summary>
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        /// <summary>
        ///     Creates a new Unsubscribe frame with the given subscription Id
        /// </summary>
        /// <param name="Id">
        ///     The Id string generated by the client when originally subscribing to this feed
        /// </param>
        public StompUnsubscribeFrame(string Id)
        {
            _id = Id;
        }
    }
}
